remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
  - label: Home 
  - README
  - label: Projects
    children:
      - Threads-Comparison
      - Shell-Implementation
  - label: Certifications
    children:
      - CompTIA-A
